#!/usr/bin/env bash
# configures domains and subdomains which makes our lives easier

prnt () {
    dig "$1" | grep -A1 'ANSWER SECTION:' | sed -r "s/$1./$2/g" | awk -F" " ' NR==2 { print "The subdomain " $1 " is a " $4 " record and points to " $5 }'
}

if [ "$#" -eq 2 ]
then
    prnt "$2.$1" "$2"
else
    prnt "www.$1" "www"
prnt "lb-01.$1" "lb-01"
    prnt "web-01.$1" "web-01"
    prnt "web-02.$1" "web-02"
fi
